export const items = [
    {
      id: "1",
      type: "MIX Rice",
      img:"../assets/cart-imgs/rice-1.png",
      size: "Medium",
      name: "chicken fried rice",
      option: "1 (chicken)",
      add_ons: ["Extra Cheese", "Extra chicken", "fied egg"],
      remove_I: ["No onions", "No mayo"],
      Rice_type: "white Rice",
      spice_lvl: "Medium",
      sauce: ["ketchup", "Spicy Mayo"],
      Dietary: "none",
      qty:2,
      total:478
    },
    {
      id: "2",
      type: "Buger",
      img:"../assets/cart-imgs/rice-1.png",
      size: "Small",
      name: "Hamburger",
      option: "2 (Beef)",
      add_ons: ["Extra Cheese", "Extra chicken", "fied egg"],
      remove_I: ["No onions", "No mayo"],
      Bun_Options: "Regular Bun",
      cooking_preference: "Medium Rare",
      sauce: ["ketchup", "Spicy Mayo"],
      Dietary: "none",
      qty:5,
      total:478
    },
    {
      id: "3",
      type: "MIX Rice",
      img:"../assets/cart-imgs/rice-1.png",
      size: "Large",
      name: "chicken fried rice",
      option: "4 (Tofu)",
      add_ons: ["None"],
      remove_I: ["No onions", "No mayo"],
      Rice_type: "Cauliflower Rice",
      spice_lvl: "Medium",
      sauce: ["Mustard"],
      Dietary: "Vegetarian",
      qty:6,
      total:478
    },
    {
      id: "4",
      type: "Buger",
      img:"../assets/cart-imgs/rice-1.png",
      size: "Medium",
      name: "Hamburger",
      option: "4 (Tofu)",
      add_ons: ["None"],
      remove_I: ["No onions", "No mayo"],
      Bun_Options: "Lettuce Wrap",
      cooking_preference: "Medium Well",
      sauce: ["Mustard", "Vegan BBQ sauce"],
      Dietary: "Vegetarian",
      qty:1,
      total:478
    }
  ];
